### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by emranch31** [WadeShuler/PHP-PayPal-IPN#18]
i got  this error : 

Array
(
    [0] => cURL error: [35] error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
)

**Comment by mksyslab** [comment]
me too.
I've read that cause of using old open-ssl version (mine is 0.9.8).  It needs 1.0.1 or more.
I'm not sure because I can't update my environment (because I'm using rental server.)
If you can, please tell the result in here, and I will change my provider. ^ ^;

**Comment by ItsTheHutch** [comment]
Yep, I can confirm, tried it with a different host with open-ssl 1.0.1e and that cURL error went away.
