### ISSUE TITLE
Certificate chain is no longer valid

### ISSUE THREAD

**Issue by ciaran-byrne** [WadeShuler/PHP-PayPal-IPN#3]
The certificate chain contained in api_cert_chain.crt file are no longer valid, cUrl requests now return the following error:

```
Errors:
Array
(
    [0] => cURL error: [60] SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
)
```
I've tested an updated version of the file using the latest contents of the cacert.pem file from the current PayPal SDK and it works fine. I can post it here or send on a copy of the file or submit a pull request if you want to add me as a contributor

**Comment by WadeShuler** [comment]
It was working as of the time I added this on GitHub. Maybe they finally killed it.

You can update the file and submit a pull request and I will merge it.

Thanks.
